### ISSUE TITLE
issue with libboost 1.62

### ISSUE THREAD

**Issue by potant** [cmbi/xssp#101]
Has anyone tried to compile with libboost 1.62?
'Configure' step passes succefully but "make" stops with the following error:
------------------------------------------------------------------------
/usr/bin/ld: cannot find -lboost_timer
collect2: error: ld returned 1 exit status
Makefile:630: recipe for target 'mkhssp' failed
-------------------------------------------------------------------------
The mkdssp is created succefully but mkhssp fails with error on -lboost_timer. Comparing the g++  commands we see:
g++  -g -O2   -o mkdssp src/dssp.o src/iocif.o src/mas.o src/mkdssp.o src/primitives-3d.o src/structure.o src/utils.o -lboost_date_time -lboost_filesystem -lboost_iostreams -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lpthread 

and 

g++  -g -O2   -o mkhssp src/blast.o src/dssp.o src/fasta.o src/fetchdbrefs.o src/hssp-nt.o src/iocif.o src/mas.o src/matrix.o src/mkhssp.o src/primitives-3d.o src/progress.o src/structure.o src/utils.o -lboost_date_time -lboost_filesystem -lboost_iostreams -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lpthread -lboost_timer -lzeep 

Trying to make separately e.g make mkdssp and make mkhssp, i take the same errors for mkhssp

Any idea?

**Comment by cbaakman** [comment]
I'm using libboost 1.62 also:
```
$ ldd mkhssp
	linux-vdso.so.1 =>  (0x00007ffcfef81000)
	libboost_date_time.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.62.0 (0x00007f6ed0bc6000)
	libboost_filesystem.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.62.0 (0x00007f6ed09ad000)
	libboost_iostreams.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.62.0 (0x00007f6ed0796000)
	libboost_program_options.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.62.0 (0x00007f6ed0519000)
	libboost_regex.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.62.0 (0x00007f6ed0208000)
	libboost_system.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.62.0 (0x00007f6ed0004000)
	libboost_thread.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.62.0 (0x00007f6ecfddd000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6ecfbbf000)
	libboost_timer.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_timer.so.1.62.0 (0x00007f6ecf9ba000)
	libzeep.so.3.0 => /usr/local/lib/libzeep.so.3.0 (0x00007f6ecf5f6000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6ecf26e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6ecef65000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6eced4e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6ece987000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6ece76b000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f6ece55b000)
	libicui18n.so.57 => /usr/lib/x86_64-linux-gnu/libicui18n.so.57 (0x00007f6ece0e1000)
	libicuuc.so.57 => /usr/lib/x86_64-linux-gnu/libicuuc.so.57 (0x00007f6ecdd39000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6ecdb31000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6ed0dd7000)
	libboost_chrono.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.62.0 (0x00007f6ecd92a000)
	libboost_random.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_random.so.1.62.0 (0x00007f6ecd724000)
	libicudata.so.57 => /usr/lib/x86_64-linux-gnu/libicudata.so.57 (0x00007f6ecbca7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6ecbaa3000)
```

mkhssp runs fine. Could you give us the error message that you get?

**Comment by potant** [comment]
here is the error
potant@potantdebian:~/Desktop/xssp-master$ make mkhssp
g++  -g -O2   -o mkhssp src/blast.o src/dssp.o src/fasta.o src/fetchdbrefs.o src/hssp-nt.o src/iocif.o src/mas.o src/matrix.o src/mkhssp.o src/primitives-3d.o src/progress.o src/structure.o src/utils.o -lboost_date_time -lboost_filesystem -lboost_iostreams -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lpthread -lboost_timer -lzeep 
/usr/bin/ld: cannot find -lboost_timer
collect2: error: ld returned 1 exit status
Makefile:630: recipe for target 'mkhssp' failed
make: *** [mkhssp] Error 1

**Comment by cbaakman** [comment]
Is libboost_timer.so present on your machine? If not you should reinstall libboost-all-dev.

**Comment by potant** [comment]
worked..
thank you.
