### ISSUE TITLE
404 error with download?

### ISSUE THREAD

**Issue by josephbedell** [cmbi/xssp#104]
I'm getting a 404 not found error when trying to wget:

>wget https://github.com/cmbi/xssp/archive/xssp-3.0.5.tar.gz

--2019-02-19 20:39:26--  https://github.com/cmbi/xssp/archive/xssp-3.0.5.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/cmbi/xssp/tar.gz/xssp-3.0.5 [following]
--2019-02-19 20:39:26--  https://codeload.github.com/cmbi/xssp/tar.gz/xssp-3.0.5
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-02-19 20:39:26 ERROR 404: Not Found.

**Comment by cbaakman** [comment]
Hello Joe,

When I try wget https://github.com/cmbi/xssp/archive/3.0.5.tar.gz it simply works.

I see that your link points to a different location:
https://codeload.github.com/cmbi/xssp/tar.gz/xssp-3.0.5

Looks like an url that doesn't exist. Where did you get it?

**Comment by josephbedell** [comment]
Thanks! That works. I got the other address from the README.md file with this project

![image](https://user-images.githubusercontent.com/21162214/53104313-c5666f00-34f4-11e9-99f2-5ca055598835.png)

**Comment by cbaakman** [comment]
That's odd, to me this link points to "https://github.com/cmbi/xssp/releases". Is it still pointing to "https://codeload.github.com/cmbi/xssp/tar.gz/xssp-3.0.5" for you?

**Comment by josephbedell** [comment]
Yes. When I go to https://github.com/cmbi/xssp/archive/xssp-3.0.5.tar.gz
it redirects me to the non-existent page of:
https://codeload.github.com/cmbi/xssp/tar.gz/xssp-3.0.5
