### ISSUE TITLE
Could not link against boost_date_time

### ISSUE THREAD

**Issue by albumns** [cmbi/xssp#113]
Hello,

I am trying to complie XSSP 3.0.8 for my Linux X64 OS. but it always failed with the following messages:

`checking for perl... perl
checking for cppcheck... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for boostlib >= 1.48... yes
checking whether the Boost::Date_Time library is available... yes
checking for exit in -lboost_date_time... yes
checking whether the Boost::Filesystem library is available... yes
configure: error: Could not link against boost_date_time !
`

**Comment by cbaakman** [comment]
This means that the boost library can be included as a header, but not linked as a library. Could be that your boost installation is incomplete. You should look for "libboost_date_time.so" on your system. if it is missing, then re-installing boost would help.

**Comment by albumns** [comment]
Hi, I found this file in my directory:

/usr/lib64/libboost_date_time.so

thanks a lot.

**Comment by cbaakman** [comment]
Can the xssp configuration file find this library?

**Comment by albumns** [comment]
probably not. Here is the full log file:

`Downloads/xssp-3.0.8> ./configure --prefix=/home/alpha/install/xssp
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for perl... perl
checking for cppcheck... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for boostlib >= 1.48... yes
checking whether the Boost::Date_Time library is available... yes
checking for exit in -lboost_date_time... yes
checking whether the Boost::Filesystem library is available... yes
configure: error: Could not link against boost_date_time !
`

**Comment by cbaakman** [comment]
Try using the '--with-boost-date-time' or '--with_boost' arguments. Type ./configure --help for more information.

**Comment by albumns** [comment]
still failed with similar errors:

```
checking for main in -lboost_date_time-/usr/lib64/libboost_date_time.so... no
configure: error: Could not link against boost_date_time-/usr/lib64/libboost_date_time.so !

```

**Comment by cbaakman** [comment]
Could you give me the output of:
```
ls -l /usr/lib64/libboost_date_time.so
```

and of 

```
uname -p
```

**Comment by albumns** [comment]
alpha/Desktop> ls -l /usr/lib64/libboost_date_time.so
lrwxrwxrwx 1 root root 28 Apr 22 13:13 /usr/lib64/libboost_date_time.so -> libboost_date_time.so.1.69.0
alpha/Desktop> uname -p
x86_64

**Comment by cbaakman** [comment]
I've made a test source file:

```
#include <iostream>
#include <string>
#include <boost/date_time/gregorian/gregorian.hpp>
#include <boost/date_time/date_formatting.hpp>
#include <boost/date_time/gregorian/greg_month.hpp>


using namespace boost::gregorian;

int main()
{
    time_t rawtime;
    struct tm *timeinfo;

    time (&rawtime);
    timeinfo = localtime (&rawtime);

    date cdate(timeinfo->tm_year+1900, timeinfo->tm_mon+1, timeinfo->tm_mday);
    cdate += date_duration(-7);

    std::string date = to_iso_string(cdate);

    std::cout << date << std::endl;

    return 0;
}
```

Could you try to compile this with:

```
g++ test.cpp -o test -lboost_date_time
```

and then tell me what happens?

**Comment by albumns** [comment]
it goes well. No any errors. I also obtained a "test" binary file.

**Comment by cbaakman** [comment]
So the boost li brary is alright. Could you tell me if there's a file named "conftest.err" in your xssp directory? If so, what are its contents?

**Comment by protein2019** [comment]
I encountered the same problem when installing hssp-3.1.5. 
I have run with `./configure --prefix=/gpfs/user/tanyh/miniconda3/envs/mutabind --with-boost=/gpfs/user/tanyh/miniconda3/envs/mutabind --with-boost-date-time=/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so` and it tells me `configure: error: Could not link against boost_date_time-/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so !`. 
The output of `ls -l /gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so` is `/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so -> libboost_date_time.so.1.67.0`
I have tried the test source file mentioned above and got no errors.

There is a file named "config.log" in my hssp directory as below.

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by hssp configure 3.1.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --prefix=/gpfs/user/tanyh/miniconda3/envs/mutabind --with-boost=/gpfs/user/tanyh/miniconda3/envs/mutabind --with-boost-date-time=/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so

## --------- ##
## Platform. ##
## --------- ##

hostname = GPU
uname -m = x86_64
uname -r = 3.10.0-327.el7.x86_64
uname -s = Linux
uname -v = #1 SMP Thu Nov 19 22:10:57 UTC 2015

/usr/bin/uname -p = x86_64
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /gpfs/user/tanyh/miniconda3/envs/mutabind/bin
PATH: /gpfs/user/tanyh/miniconda3/condabin
PATH: /usr/lib64/qt-3.3/bin
PATH: /home/tanyh/perl5/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /usr/local/sbin
PATH: /usr/sbin
PATH: /opt/ibutils/bin
PATH: /usr/local/cuda/bin
PATH: /gpfs/user/tanyh/ensembl-vep
PATH: /home/tanyh/.local/bin
PATH: /home/tanyh/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2530: checking for a BSD-compatible install
configure:2598: result: /usr/bin/install -c
configure:2609: checking whether build environment is sane
configure:2664: result: yes
configure:2815: checking for a thread-safe mkdir -p
configure:2854: result: /usr/bin/mkdir -p
configure:2861: checking for gawk
configure:2877: found /usr/bin/gawk
configure:2888: result: gawk
configure:2899: checking whether make sets $(MAKE)
configure:2921: result: yes
configure:2950: checking whether make supports nested variables
configure:2967: result: yes
configure:3115: checking for g++
configure:3131: found /usr/bin/g++
configure:3142: result: g++
configure:3169: checking for C++ compiler version
configure:3178: g++ --version >&5
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3189: $? = 0
configure:3178: g++ -v >&5
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
configure:3189: $? = 0
configure:3178: g++ -V >&5
g++: error: unrecognized command line option '-V'
g++: fatal error: no input files
compilation terminated.
configure:3189: $? = 4
configure:3178: g++ -qversion >&5
g++: error: unrecognized command line option '-qversion'
g++: fatal error: no input files
compilation terminated.
configure:3189: $? = 4
configure:3209: checking whether the C++ compiler works
configure:3231: g++    conftest.cpp  >&5
configure:3235: $? = 0
configure:3283: result: yes
configure:3286: checking for C++ compiler default output file name
configure:3288: result: a.out
configure:3294: checking for suffix of executables
configure:3301: g++ -o conftest    conftest.cpp  >&5
configure:3305: $? = 0
configure:3327: result: 
configure:3349: checking whether we are cross compiling
configure:3357: g++ -o conftest    conftest.cpp  >&5
configure:3361: $? = 0
configure:3368: ./conftest
configure:3372: $? = 0
configure:3387: result: no
configure:3392: checking for suffix of object files
configure:3414: g++ -c   conftest.cpp >&5
configure:3418: $? = 0
configure:3439: result: o
configure:3443: checking whether we are using the GNU C++ compiler
configure:3462: g++ -c   conftest.cpp >&5
configure:3462: $? = 0
configure:3471: result: yes
configure:3480: checking whether g++ accepts -g
configure:3500: g++ -c -g  conftest.cpp >&5
configure:3500: $? = 0
configure:3541: result: yes
configure:3575: checking for style of include used by make
configure:3603: result: GNU
configure:3629: checking dependency style of g++
configure:3740: result: gcc3
configure:3803: checking for gcc
configure:3819: found /usr/bin/gcc
configure:3830: result: gcc
configure:4059: checking for C compiler version
configure:4068: gcc --version >&5
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:4079: $? = 0
configure:4068: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
configure:4079: $? = 0
configure:4068: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4079: $? = 4
configure:4068: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:4079: $? = 4
configure:4083: checking whether we are using the GNU C compiler
configure:4102: gcc -c   conftest.c >&5
configure:4102: $? = 0
configure:4111: result: yes
configure:4120: checking whether gcc accepts -g
configure:4140: gcc -c -g  conftest.c >&5
configure:4140: $? = 0
configure:4181: result: yes
configure:4198: checking for gcc option to accept ISO C89
configure:4261: gcc  -c -g -O2  conftest.c >&5
configure:4261: $? = 0
configure:4274: result: none needed
configure:4296: checking dependency style of gcc
configure:4407: result: gcc3
configure:4427: checking for perl
configure:4443: found /usr/bin/perl
configure:4454: result: perl
configure:4474: checking for cppcheck
configure:4504: result: no
configure:4523: checking build system type
configure:4537: result: x86_64-unknown-linux-gnu
configure:4557: checking host system type
configure:4570: result: x86_64-unknown-linux-gnu
configure:4639: checking for boostlib >= 1.54
configure:4719: g++ -c -g -O2  -I/gpfs/user/tanyh/miniconda3/envs/mutabind/include conftest.cpp >&5
configure:4719: $? = 0
configure:4721: result: yes
configure:4899: checking whether the Boost::Date_Time library is available
configure:4923: g++ -c -g -O2  -I/gpfs/user/tanyh/miniconda3/envs/mutabind/include conftest.cpp >&5
configure:4923: $? = 0
configure:4937: result: yes
configure:5045: checking for main in -l/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so
configure:5064: gcc -o conftest -g -O2  -I/gpfs/user/tanyh/miniconda3/envs/mutabind/include  -L/gpfs/user/tanyh/miniconda3/envs/mutabind/lib conftest.c -l/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so   >&5
/usr/bin/ld: cannot find -l/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so
collect2: error: ld returned 1 exit status
configure:5064: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "hssp"
| #define PACKAGE_TARNAME "hssp"
| #define PACKAGE_VERSION "3.1.0"
| #define PACKAGE_STRING "hssp 3.1.0"
| #define PACKAGE_BUGREPORT "Coos.Baakman@radboudumc.nl"
| #define PACKAGE_URL ""
| #define PACKAGE "hssp"
| #define VERSION "3.1.0"
| #define HAVE_BOOST /**/
| #define HAVE_BOOST_DATE_TIME /**/
| /* end confdefs.h.  */
| 
| 
| int
| main ()
| {
| return main ();
|   ;
|   return 0;
| }
configure:5074: result: no
configure:5045: checking for main in -lboost_date_time-/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so
configure:5064: gcc -o conftest -g -O2  -I/gpfs/user/tanyh/miniconda3/envs/mutabind/include  -L/gpfs/user/tanyh/miniconda3/envs/mutabind/lib conftest.c -lboost_date_time-/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so   >&5
/usr/bin/ld: cannot find -lboost_date_time-/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so
collect2: error: ld returned 1 exit status
configure:5064: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "hssp"
| #define PACKAGE_TARNAME "hssp"
| #define PACKAGE_VERSION "3.1.0"
| #define PACKAGE_STRING "hssp 3.1.0"
| #define PACKAGE_BUGREPORT "Coos.Baakman@radboudumc.nl"
| #define PACKAGE_URL ""
| #define PACKAGE "hssp"
| #define VERSION "3.1.0"
| #define HAVE_BOOST /**/
| #define HAVE_BOOST_DATE_TIME /**/
| /* end confdefs.h.  */
| 
| 
| int
| main ()
| {
| return main ();
|   ;
|   return 0;
| }
configure:5074: result: no
configure:5089: error: Could not link against boost_date_time-/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so !

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_c_compiler_gnu=yes
ac_cv_cxx_compiler_gnu=yes
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBBZ2_CPPFLAGS_set=
ac_cv_env_LIBBZ2_CPPFLAGS_value=
ac_cv_env_LIBBZ2_LDFLAGS_set=
ac_cv_env_LIBBZ2_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LIBZ_CPPFLAGS_set=
ac_cv_env_LIBZ_CPPFLAGS_value=
ac_cv_env_LIBZ_LDFLAGS_set=
ac_cv_env_LIBZ_LDFLAGS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_lib__gpfs_user_tanyh_miniconda3_envs_mutabind_lib_libboost_date_time_so___main=no
ac_cv_lib_boost_date_time__gpfs_user_tanyh_miniconda3_envs_mutabind_lib_libboost_date_time_so___main=no
ac_cv_objext=o
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/usr/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_PERL=perl
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_ac_ct_CXX=g++
ac_cv_prog_cc_c89=
ac_cv_prog_cc_g=yes
ac_cv_prog_cxx_g=yes
ac_cv_prog_make_make_set=yes
am_cv_CC_dependencies_compiler_type=gcc3
am_cv_CXX_dependencies_compiler_type=gcc3
am_cv_make_support_nested_variables=yes
ax_cv_boost_date_time=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /gpfs/user/tanyh/mutabindm/hssp-3.1.5/missing aclocal-1.13'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AUTOCONF='${SHELL} /gpfs/user/tanyh/mutabindm/hssp-3.1.5/missing autoconf'
AUTOHEADER='${SHELL} /gpfs/user/tanyh/mutabindm/hssp-3.1.5/missing autoheader'
AUTOMAKE='${SHELL} /gpfs/user/tanyh/mutabindm/hssp-3.1.5/missing automake-1.13'
AWK='gawk'
BOOST_CPPFLAGS='-I/gpfs/user/tanyh/miniconda3/envs/mutabind/include'
BOOST_DATE_TIME_LIB=''
BOOST_FILESYSTEM_LIB=''
BOOST_IOSTREAMS_LIB=''
BOOST_LDFLAGS='-L/gpfs/user/tanyh/miniconda3/envs/mutabind/lib'
BOOST_PROGRAM_OPTIONS_LIB=''
BOOST_REGEX_LIB=''
BOOST_SYSTEM_LIB=''
BOOST_THREAD_LIB=''
BOOST_TIMER_LIB=''
BOOST_UNIT_TEST_FRAMEWORK_LIB=''
CC='gcc'
CCDEPMODE='depmode=gcc3'
CFLAGS='-g -O2'
CPP=''
CPPCHECK='yes'
CPPFLAGS=' -I/gpfs/user/tanyh/miniconda3/envs/mutabind/include'
CXX='g++'
CXXDEPMODE='depmode=gcc3'
CXXFLAGS='-g -O2'
CYGPATH_W='echo'
DEFS=''
DEPDIR='.deps'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
GREP=''
HAVE_CPPCHECK_FALSE=''
HAVE_CPPCHECK_TRUE=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LDFLAGS=' -L/gpfs/user/tanyh/miniconda3/envs/mutabind/lib'
LIBBZ2_CPPFLAGS=''
LIBBZ2_LDFLAGS=''
LIBOBJS=''
LIBS=''
LIBZ_CPPFLAGS=''
LIBZ_LDFLAGS=''
LTLIBOBJS=''
MAKEINFO='${SHELL} /gpfs/user/tanyh/mutabindm/hssp-3.1.5/missing makeinfo'
MKDIR_P='/usr/bin/mkdir -p'
OBJEXT='o'
PACKAGE='hssp'
PACKAGE_BUGREPORT='Coos.Baakman@radboudumc.nl'
PACKAGE_NAME='hssp'
PACKAGE_STRING='hssp 3.1.0'
PACKAGE_TARNAME='hssp'
PACKAGE_URL=''
PACKAGE_VERSION='3.1.0'
PATH_SEPARATOR=':'
PERL='perl'
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
USE_FETCH_DBREFS_FALSE=''
USE_FETCH_DBREFS_TRUE=''
VERSION='3.1.0'
ac_ct_CC='gcc'
ac_ct_CXX='g++'
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE='#'
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE='#'
am__fastdepCXX_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /gpfs/user/tanyh/mutabindm/hssp-3.1.5/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/gpfs/user/tanyh/miniconda3/envs/mutabind'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "hssp"
#define PACKAGE_TARNAME "hssp"
#define PACKAGE_VERSION "3.1.0"
#define PACKAGE_STRING "hssp 3.1.0"
#define PACKAGE_BUGREPORT "Coos.Baakman@radboudumc.nl"
#define PACKAGE_URL ""
#define PACKAGE "hssp"
#define VERSION "3.1.0"
#define HAVE_BOOST /**/
#define HAVE_BOOST_DATE_TIME /**/

configure: exit 1

**Comment by cbaakman** [comment]
The --with-boost-date-time configure option is not supposed to be given a full library path. It should just contain the name of the library, without the 'lib' prefix and the '.so' suffix. Example:

```
./configure --with-boost-date-time=boost_date_time-gcc-mt-d-1_33_1
```

I don't think you need to use that option here, since your library file has the default name.

Check ```./configure --help``` for further details.

**Comment by protein2019** [comment]
Thanks for your help. I try it without `with-boost-date-time` and get the same error, but the content in "config.log" is different this time.

configure:4948: checking for exit in -lboost_date_time
configure:4973: gcc -o conftest -g -O2  -I/gpfs/user/tanyh/miniconda3/envs/mutabind/include  -L/gpfs/user/tanyh/miniconda3/envs/mutabind/lib conftest.c -lboost_date_time   >&5
conftest.c:20:6: warning: conflicting types for built-in function 'exit' [enabled by default]
 char exit ();
      ^
/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so: undefined reference to `std::out_of_range::out_of_range(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
/gpfs/user/tanyh/miniconda3/envs/mutabind/lib/libboost_date_time.so: undefined reference to `std::logic_error::logic_error(std::logic_error const&)@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
configure:4973: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "hssp"
| #define PACKAGE_TARNAME "hssp"
| #define PACKAGE_VERSION "3.1.0"
| #define PACKAGE_STRING "hssp 3.1.0"
| #define PACKAGE_BUGREPORT "Coos.Baakman@radboudumc.nl"
| #define PACKAGE_URL ""
| #define PACKAGE "hssp"
| #define VERSION "3.1.0"
| #define HAVE_BOOST /**/
| #define HAVE_BOOST_DATE_TIME /**/
| /* end confdefs.h.  */
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char exit ();
| int
| main ()
| {
| return exit ();
|   ;
|   return 0;
| }
configure:4983: result: no
configure:4948: checking for exit in -lboost_date_time
configure:4983: result: no
configure:4948: checking for exit in -lboost_date_time
configure:4983: result: no
configure:5089: error: Could not link against boost_date_time !
