### ISSUE TITLE
Failed to connect to download the data 

### ISSUE THREAD

**Issue by shahryary** [cmbi/xssp#134]
I'm continuously getting an error when I try to download the data. I've also tried both rsync and FTP, but it doesn't work. 

Could you please check if the server is available?

```
rsync: failed to connect to rsync.cmbi.umcn.nl (131.174.161.51): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.3]
```

**Comment by cbaakman** [comment]
FTP is working. rsync is indeed down. We're working on it..

**Comment by cbaakman** [comment]
rsync is back online. Thanks for waiting.
