### ISSUE TITLE
Unused files

### ISSUE THREAD

**Issue by jonblack** [cmbi/xssp#15]
The following files are not used during compilation. Are they needed. If so, what for?
- align-2d.cpp
- align-3d.cpp
- maxhom-hssp.cpp
- mutualinformation.cpp
- ioseq.cpp
- guide.cpp
- mkhssp.h

**Comment by cbaakman** [comment]
Looks like the remains of Maarten's attempts to write different alignment methods. They are not needed right now.

**Comment by jonblack** [comment]
Can you remove them, please?

**Comment by cbaakman** [comment]
This was done in #87
