### ISSUE TITLE
DSSP could not be created due to an error: basic_string::substr

### ISSUE THREAD

**Issue by jonblack** [cmbi/xssp#33]
During a call to `mkdssp` using a pdb_file in xssp-rest, the following error was reported:

    DSSP could not be created due to an error: basic_string::substr

**Comment by jonblack** [comment]
I suspect this was fixed in 2.2.6.

**Comment by touwwouter** [comment]
The issue has to be more specific since this can happen at many locations where `substr` is used. We indeed fixed some of them. Open a new issue when we see the problem again.
