### ISSUE TITLE
Support coordinate-only PDB files

### ISSUE THREAD

**Issue by touwwouter** [cmbi/xssp#52]
The ATOM records of coordinate-only PDB files (e.g. without occupancy and temperature factor) are only 54 characters long.
The following error is raised
```
DSSP could not be created due to an error:
basic_string::substr
```
Because of the [line](https://github.com/cmbi/xssp/blob/39c8c7845d417e227afbc45fa68a070979b9d516/src/structure.cpp#L1206)
```
atom.mOccupancy = ParseFloat(line.substr(54, 6));
```

Strangely, records of length 60, i.e. without B-factors, can be parsed without errors even though we have the [line](https://github.com/cmbi/xssp/blob/39c8c7845d417e227afbc45fa68a070979b9d516/src/structure.cpp#L1208)
```
atom.mTempFactor = ParseFloat(line.substr(60, 6));
```

As far as I can see, occupancy is never used (e.g. for quality checks) except for writing PDB files in align-3d.cpp (for testing?).
Therefore, PDB files with ATOM records of length 54 should be supported.

(adjust mmCIF parser accordingly if necessary)

**Comment by jonblack** [comment]
The first failure isn't because of parsing the occupancy. It fails because it cannot parse the tempFactor. The test case where there is an occupancy but no tempFactor works because strings are terminated with `/0`, which is not included in the length but can be read without error.
