### ISSUE TITLE
mkdssp: handle missing B-factors

### ISSUE THREAD

**Issue by cbaakman** [cmbi/xssp#54]
The mkdssp 2.2.5 crashes when a pdb_redo file misses a B-factor. The Kabsch&Sander version of mkdssp does work.

```
$ /usr/local/bin/mkdssp /data/pdb_redo/zj/2zjp/2zjp_final.pdb /data/dssp_redo/2zjp.dssp

DSSP could not be created due to an error:
invalid formatted floating point number '******'
```

PDB file:
```
ATOM  84394  OP2 U   Z 123      92.874 107.226  -3.165  1.00 42.24           O
HETATM84395 ZN   ZN  4  38      93.819  72.980 102.664  1.00******          ZN
```

**Comment by touwwouter** [comment]
According to #52 B-factors are allowed to be missing, but this issue suggests that if B-factors are present, they should be parsable, i.e. have meaningful values.
