### ISSUE TITLE
hsspconv segfault

### ISSUE THREAD

**Issue by cbaakman** [cmbi/xssp#56]
hsspconv segfaults for the two input files: 4s1h.hssp.bz2 and 4s1m.hssp.bz2.

[4s1h.hssp.txt](https://github.com/cmbi/xssp/files/639089/4s1h.hssp.txt)
[4s1m.hssp.txt](https://github.com/cmbi/xssp/files/639090/4s1m.hssp.txt)

**Comment by jonblack** [comment]
@cbaakman Is this still the case? If so, can you look into the cause and provide a fix (with unit test)?

**Comment by cbaakman** [comment]
The files have unallowed line breaks, I'll make hsspconv throw an exception for these files.
