### ISSUE TITLE
mtrx/matrices.h not generated correctly

### ISSUE THREAD

**Issue by jonblack** [cmbi/xssp#72]
Unpacking the release and building works find. Running `make clean` removes `mtrx/matrices.h`. Rebuilding with `make` then fails with the following error:

```
In file included from src/matrix.cpp:11:0:
src/../mtrx/matrices.h:15:1: error: zero-size array 'kMatrices'
 };
 ^
```

**Comment by jonblack** [comment]
This may already have been fixed by me in develop.

**Comment by jonblack** [comment]
@cbaakman Can you check that this is fixed?

**Comment by cbaakman** [comment]
There is no develop branch in xssp. Do you still have a copy of `mtrx/matrices.h`?

**Comment by jonblack** [comment]
Did you download the release archive and try to compile it?

**Comment by jonblack** [comment]
I think the problem is in the release archive. Can you try to download and compile that?

**Comment by cbaakman** [comment]
If the problem is in the release, then can't you just remove the release and make a new one from the master branch?

**Comment by jonblack** [comment]
If it works in docker, it's fixed.
