### ISSUE TITLE
mmCIF chain ids

### ISSUE THREAD

**Issue by cbaakman** [cmbi/xssp#74]
When dssp files are created from mmCIF files, the chain ID's aren't correctly displayed. An example is 3j9m.dssp. Only the first character of the chain ID is given.

**Comment by drlemmus** [comment]
Unfortunately this is unsolvable without changing the DSSP format. The mmCIF format allows 4-character chain ID's which cannot be mapped back to the maximum 62 possible CHAINids in the PDB format.

Changing the DSSP format can also fit the dual numbering schemes of the mmCIF files. That we we can retain the depositor's numbering and at the same time follow a more sensible numbering of our own design.

**Comment by touwwouter** [comment]
In the current [mmCIF/PDBx dictionary](http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v40.dic/Categories/atom_site.html) `_atom_site.label_asym_id` and `_atom_site.auth_asym_id` are both mandatory data items, so it would make sense to include them both (together with the other mandatory as well as currently used data items). I will open a new issue for changing the DSSP format.

**Comment by cbaakman** [comment]
This has been done in version 3.0.0, since https://github.com/cmbi/xssp/commit/6fcc9786dd6a3ee02e5964129ccd42041feef52c
