### ISSUE TITLE
Change DSSP format

### ISSUE THREAD

**Issue by touwwouter** [cmbi/xssp#75]
The transition from the old PDB format to mmCIF/PDBx poses some issues:
- Multi-character chain identifiers in mmCIF files do not fit the single column in the current DSSP format (see #74)
- In the current [mmCIF/PDBx dictionary](http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v40.dic/Categories/atom_site.html) the are `_atom_site.label_<...>` and `_atom_site.auth_<...>` data items to identify `_atom_site`s. To provide backward and forward compatibility it would make sense to include the mandatory items and the currently used items in a new DSSP format (the current DSSP format also lacks model numbers, for example).

Perhaps a command line option `format` can be added with two allowed values, `new` and `old` (default).

**Comment by cbaakman** [comment]
Version 3 of xssp produces new formats now.
