### ISSUE TITLE
Recent whitespace changes break column layout

### ISSUE THREAD

**Issue by tonyelewis** [cmbi/xssp#81]
The neatly aligned columns appear to have been broken by 9de0ce4d65728be188770229c07b340aed07e39d.

Eg, in the parent commit f75bcb29a39337ec124333ed8aadc866f55784a8, the results from the 44th column onward look like:

~~~~~
N-H-->O    O-->H-N    N-H-->O    O-->H-N    TCO  KAPPA ALPHA  PHI   PSI    X-CA   Y-CA   Z-CA 
 0, 0.0     0, 0.0     0, 0.0     0, 0.0   0.000 360.0 360.0 360.0 360.0   24.1    4.5   -6.0
 0, 0.0     0, 0.0     0, 0.0     0, 0.0   0.000 360.0 360.0 360.0 360.0    0.0    0.0    0.0
 0, 0.0     0, 0.0     0, 0.0     0, 0.0   0.000 360.0 360.0 360.0 360.0   26.8    0.8   -8.6
~~~~~

....whereas in 9de0ce4d65728be188770229c07b340aed07e39d, they look like:

~~~~~
N-H-->O    O-->H-N N-H-->O    O-->H-N    TCO  KAPPA ALPHA  PHI   PSI    X-CA   Y-CA   Z-CA            CHAIN
 0, 0.0     0, 0.0     0, 0.0     0, 0.0  0.000 360.0 360.0 360.0 360.0   24.1    4.5   -6.0               
 0, 0.0     0, 0.0     0, 0.0     0, 0.0   0.000 360.0 360.0 360.0 360.0    0.0    0.0    0.0
 0, 0.0     0, 0.0     0, 0.0     0, 0.0  0.000 360.0 360.0 360.0 360.0   26.8    0.8   -8.6               
~~~~~

From what I can see, this just looks to be caused by the removal of a few whitespace characters around lines [36](https://github.com/cmbi/xssp/blob/9de0ce4d65728be188770229c07b340aed07e39d/src/dssp.cpp#L36) and [219](https://github.com/cmbi/xssp/blob/9de0ce4d65728be188770229c07b340aed07e39d/src/dssp.cpp#L219).

**Comment by cbaakman** [comment]
Hello @tonyelewis, could you provide the pdb id of the file that shows the bug? I need to know for testing purposes.

**Comment by tonyelewis** [comment]
I'm guessing it'd apply to most PDBs but yes, I'll find and post the ID of the PDB that motivated me raising the issue when I'm at a computer.

Thanks.

**Comment by tonyelewis** [comment]
I was motivated to raise this issue when looking at PDB 1sx2 (actually a subset of 1sx2's lines in a testcase relating to #79).

**Comment by tonyelewis** [comment]
Great - thanks very much for this.
