### ISSUE TITLE
FTP broken

### ISSUE THREAD

**Issue by guma44** [cmbi/xssp#96]
Hi,

Thanks for good software. It seems that the your FTP server is broken. ftp://ftp.cmbi.ru.nl//pub/molbio/data/dssp/ no longer responds.

Best,
Rafal

**Comment by cbaakman** [comment]
Dear user,
The ftp has moved.
You can find it at:

ftp://ftp.cmbi.umcn.nl/molbio/data/dssp/

**Comment by guma44** [comment]
Thanks, it is working now.
