### ISSUE TITLE
Update Linux binaries

### ISSUE THREAD

**Issue by dunatotatos** [cmbi/xssp#98]
Hi all,

I've tried to compile xssp on CentOS, but I'm stuck due to the lack of libzeep on this OS. I'm therefore trying to find an complied binary, but the last (and only) version available on the [FTP](ftp://ftp.cmbi.ru.nl/pub/software/dssp/) is pretty old.

Could you update the binaries on the FTP, or let me know where to find it?

**Comment by cbaakman** [comment]
The best is to download libzeep from github:
https://github.com/mhekkel/libzeep/releases

**Comment by dunatotatos** [comment]
I've got it to work. The process is not straigthforward, as libzeep provides `libzeep.so.3.0`, but xssp looks for `libzeep.so`.
One has to create a symlink (or copy the file) to get the xssp compilation to succeed.

Thanks for your answer!
